feat: settling aave pools
Voltz-Protocol/voltz-ui pull request #757
Opened 2023-08-14 16:47 UTC by ioanaroceanu2000

# Title

Enable settling of Aave pools

2023-08-14 16:59 UTC, avniculae approved these changes

2023-08-14 17:09 UTC, ssbarbee commented on src/app/features/settle-flow/selectors.ts
> +export const selectIsAaveAugust = (state: RootState): boolean => {
```suggestion
export const selectIsSettlementAllowedWhenPaused; = (state: RootState): boolean => {
```

2023-08-14 17:10 UTC, ssbarbee commented on src/app/features/settle-flow/selectors.ts
> +  // todo: rename this flag
remove todo or do it now :)

2023-08-14 17:10 UTC, ssbarbee commented on src/ui/components/SettleFlow/SettleConfirmationStep/index.tsx
>              ? 'Pool paused until further notice. Check Discord for updates.'
```suggestion
            ? 'Pool settlement paused until further notice. Check Discord for updates.'
```

2023-08-14 17:59 UTC, ssbarbee requested changes
reduce the amount of changes in yarn.lock... this can break entire application. 

seems as stuff was coming from registry.npmjs.org
but now comes from registry.yarnpkg.com

let's make sure this remains the case.

2023-08-15 07:56 UTC, ssbarbee approved these changes

2023-08-15 08:01 UTC, closed without merging